// coding: cp866
//---------------------------------------------------------------------------
// Файл исходных сообщений программы CODUS
uc SMSG[MMSG+1][SLEN]={
/* 000 */ "D: Ok!",
/* 001 */ "C: Programm  'CODUS' already  run!",
/* 002 */ "D: Time start programm CODUS: %s %s",
/* 003 */ "D: Version %.4f %s",
/* 004 */ "D: System initialization...",
/* 005 */ "D: Reading configure & system files...",
/* 006 */ "D: System files CRC error.",
/* 007 */ "D: Check free memory...",
/* 008 */ "D: Set graphics mode...",
/* 009 */ "C: This is console for run programm 'CODUS'.",
/* 010 */ "D: Timer initialization...",
/* 011 */ "D: %s: Jump to begin cycle.",
/* 012 */ "D: %s: Very mach signals exclude situations.",
/* 013 */ "D: %s: Not initialize flag signals exclude situations.",
/* 014 */ "D: Run cycle functions.",
/* 015 */ "D: Begin configuration read.",
/* 016 */ "D: End configuration read.",
/* 017 */ "",
/* 018 */ "",
/* 019 */ "",
/* 020 */ "D: Begin function Mexit. Release memory graphics occupied.",
/* 021 */ "D: Close graphics library.",
/* 022 */ "D: Write flag end programm.",
/* 023 */ "D: Stop network interfaces.",
/* 024 */ "D: Fault delete workstation name from NetBIOS list [%s:%d].",
/* 025 */ "D: Write last message about exit programm.",
/* 026 */ "D: Close current database files.",
/* 027 */ "D: Write archive buffers.",
/* 028 */ "D: Close database archive & report.",
/* 029 */ "D: Time exit from programm CODUS: %s %s",
/* 030 */ "D: Defined user command file name: [%s].",
/* 031 */ "D: ERROR open DATA file [%s]",
/* 032 */ "D: ##### Information readed from project messages file [%s]:",
/* 033 */ "D: USER COMMAND (*.CMD) FILE: [%s].",
/* 034 */ "D: ##### Information readed from channels base file [%s]:",
/* 035 */ "D: Numbers channels for archivation:",
/* 036 */ "D: Numbers channels for request into COM port:",
/* 037 */ "D: Numbers channels for request  NETBIOS:",
/* 038 */ "D: ##### Archivated channels:",
/* 039 */ "D: Total channels for archivation: %d",
/* 040 */ "D: Access denied for user command file [%s].",
/* 041 */ "D: Readed %d bytes from user command file [%s].",
/* 042 */ "D: Open error user command file [%s].",
/* 043 */ "D: ERROR read user command file [%s].",
/* 044 */ "",
/* 045 */ "D: Begin read configuration file:",
/* 046 */ "D: Variable clearing",
/* 047 */ "E: ERROR open file [%s]",
/* 048 */ "D: Analisis configuration file [%s] ------------",
/* 049 */ "D: Loading sprites...",
/* 050 */ "D: Loading primitives...",
/* 051 */ "D: Loading scales...",
/* 052 */ "D: Loading strings...",
/* 053 */ "D: Loading files views...",
/* 054 */ "D: Loading variables views...",
/* 055 */ "D: Loading histograms...",
/* 056 */ "D: Loading the buttons menu...",
/* 057 */ "D: Mistake to activations sprite buttons menu.",
/* 058 */ "D: Loading menu...",
/* 059 */ "D: Loading trends...",
/* 060 */ "D: Reading archive into trends...",
/* 061 */ "D: Loading crawler...",
/* 062 */ "D: Loading request...",
/* 063 */ "D: Loading animation...",
/* 064 */ "D: ERROR initialization COM%d",
/* 065 */ "D: Port COM%d initialized on baud:%d",
/* 066 */ "D: ERROR initialization COM%d [Code=%d].",
/* 067 */ "D: NetBIOS driver defined, but not loaded.",
/* 068 */ "D: Can not be installed name [%s:%d] for workstation NetBIOS.",
/* 069 */ "D: Installation of initial importances request.",
/* 070 */ "D: Loaded configure end.",
/* 071 */ "D: ERROR open index file [%s].",
/* 072 */ "D: Analisis printer command file descriptions:",
/* 073 */ "D: ERROR in archive file [%s] corrected. [C=%ld, %d of %ld].",
/* 074 */ "D: Not found free areas for work with database report [Sel=%d Buf=%d].",
/* 075 */ "D: Create database report.",
/* 076 */ "D: ERROR create database report [%s][R=%d].",
/* 077 */ "D: Report database created.",
/* 078 */ "D: Opening database report.",
/* 079 */ "D: ERROR open database report [%s][R=%d].",
/* 080 */ "D: Database report opened.",
/* 081 */ "D: Not free areas for work with archive database.",
/* 082 */ "D: Create archive database.",
/* 083 */ "D: ERROR create database [%s].",
/* 084 */ "D: Archive database created.",
/* 085 */ "D: Opening archive database.",
/* 086 */ "D: ERROR open archive database [%s].",
/* 087 */ "D: Archive database opened.",
/* 088 */ "D: Analisis user command file:",
/* 089 */ "D: ERROR install graphic modes for permit: %dx%d.",
/* 090 */ "D: Set graphics mode: %c:%dx%d.",
/* 091 */ "D: ERROR loaded data file [%s].",
/* 092 */ "D: ERROR loaded logotype file [%s].",
/* 093 */ " Инициализация",
/* 094 */ "D: ERROR create menu buttons [MKNP=%d WKNP=%d a=%d b=%d].",
/* 095 */ "D: ERROR create images under animations (1).",
/* 096 */ "D: ERROR create images under animations (2).",
/* 097 */ "D: ERROR create images under crawler (1) [MPLZ=%d WPLZ=%d a=%d].",
/* 098 */ "D: ERROR create images under crawler (2) [MPLZ=%d WPLZ=%d a=%d b=%d].",
/* 099 */ "D: Free memory PLZ.",
/* 100 */ "D: Free memory ANI.",
/* 101 */ "D: Free memory KNP.",
/* 102 */ "D: Free memory SPR.",
/* 103 */ "D: Free memory CUR.",
/* 104 */ "D: Free memory SCR.",
/* 105 */ "D: Ends free memory.",
/* 106 */ "D: ERROR load file [%s].",
/* 107 */ "D: Not defined work string file name.",
/* 108 */ "S: Не задана рабочая строка имени файла.",
/* 109 */ "S: Ошибка записи экрана в файл [%s].",
/* 110 */ "S: Экран записан в файл [%s].",
/* 111 */ "D: Not defined file name for save screen [ws=%d].",
/* 112 */ "S: Не определено имя файла для сохранения экрана.",
/* 113 */ "D: Defined channel[%d] FSRS=%d CB.t=%d for set value.",
/* 114 */ "D: Not defined type channel for requests under COM [CSSER=%d FSRS=%d CB.t=%d].",
/* 115 */ "S: Введена неверная дата...",
/* 116 */ "S: Не закончен предыдущий поиск.",
/* 117 */ "S: Введено неверное время...",
/* 118 */ "S: Ошибка доступа к файлу отчета [%s].",
/* 119 */ "S: Введена неверная дата.",
/* 120 */ "S: Ошибка открытия индексного файла [%s]",
/* 121 */ "S: Идет поиск данных...",
/* 122 */ "S: Поиск закончен. Данные НЕ НАЙДЕНЫ.",
/* 123 */ "S: Поиск закончен. Данные НАЙДЕНЫ!",
/* 124 */ "D: Not free areas for work with archive database.",
/* 125 */ "S: Ошибка открытия файла [%s].",
/* 126 */ "S: Открыт файл архива [%s].",
/* 127 */ "S: Текущий файл архива.",
/* 128 */ "D: Can not open archives file [%s].",
/* 129 */ "S: Нельзя открыть файл архива [%s].",
/* 130 */ "D: Can not open report file [%s].",
/* 131 */ "S: Нельзя открыть файл отчета [%s].",
/* 132 */ "S: Введите данные и нажмите ENTER. Отмена ввода-ESC.",
/* 133 */ " ",
/* 134 */ "D: Begin check free place on drive CDrive=%c.",
/* 135 */ "D: End check free place on drive.",
/* 136 */ "D: Size free place on drive[%d] less specified[%d].",
/* 137 */ "D: Number files[%d] greate specified[%d].",
/* 138 */ "D: Remove archive files %s/arc/%s.*",
/* 139 */ "D: Check free place on drive finish.",
/* 140 */ "D: Count archive files: present[%d] specified[%d].",
/* 141 */ "D: Free place on drive: present[%d] specified[%d].",
/* 142 */ "E: Не найден файл [%s].",
/* 143 */ "D: Not found file [%s].",
/* 144 */ "E: Ошибка открытия файла БД [%s].",
/* 145 */ "D: ERROR open database file [%s].",
/* 146 */ "S: Открыт файл отчета [%s].",
/* 147 */ "S: Не определена строка поиска.",
/* 148 */ "S: Идет прямой поиск строки...",
/* 149 */ "S: Идет обратный поиск строки...",
/* 150 */ "S: Поиск строки закончен. Строка НАЙДЕНА!!!",
/* 151 */ "S: Поиск строки закончен. Строка НЕ НАЙДЕНА!!!",
/* 152 */ "D: Run programm [%s].",
/* 153 */ "D: ERROR read FRM file for report generate [%s].",
/* 154 */ "S: Ошибка открытия файла [%s].",
/* 155 */ "D: ERROR create report table [%s].",
/* 156 */ "D: ERROR open report table [%s]",
/* 157 */ "S: Печать остановлена.",
/* 158 */ "S: Начало печати.",
/* 159 */ "S: Статус принтера: ТаймАут.",
/* 160 */ "S: Статус принтера: Ошибка ввода/вывода.",
/* 161 */ "S: Статус принтера: Нет бумаги.",
/* 162 */ "S: Статус принтера: Нет связи.",
/* 163 */ "S: Статус принтера: Занят.",
/* 164 */ "S: Статус принтера: обработана строка %d из %d",
/* 165 */ "S: Печать закончена. Обработано строк: %d",
/* 166 */ "D: For load variables need %d byte in memory.",
/* 167 */ "D: For load graphics need %d byte in memory (not video).",
/* 168 */ "D: ERROR allocate memory.",
/* 169 */ "D: Set record number [pr=%ld RecCount=%d].",
/* 170 */ "D: Trend array clear.",
/* 171 */ "D: Fill trend array from records archive database:",
/* 172 */ "D: Out of database records range [record N%d].",
/* 173 */ "D: ERROR[%fr] read data from record N%d.",
/* 174 */ "D: Not find field [N%d fn=%d].",
/* 175 */ "S: Файл для записи сообщений закрыт.",
/* 176 */ "S: Файл для записи сообщений закрыт.",
/* 177 */ "S: Запись экрана в файл %s ...",
/* 178 */ "D: Not found file FCHOICE command [%s]",
/* 179 */ "D: Variable [%s] not defined in global chanel base.",
/* 180 */ "[%s] [%s] [%s]",
/* 181 */ "",
/* 182 */ "",
/* 183 */ "",
/* 184 */ "",
/* 185 */ "",
/* 186 */ "",
/* 187 */ "",
/* 188 */ "",
/* 189 */ "",
/* 190 */ "",
/* 191 */ "",
/* 192 */ "",
/* 193 */ "",
/* 194 */ "",
/* 195 */ "",
/* 196 */ "",
/* 197 */ "",
/* 198 */ "",
/* 199 */ ""
};
